# These are supported funding model platforms

github: [alexandrsukhryn]
# ko_fi: # Replace with: ko_fi: your-username
# open_collective: # Replace with: open_collective: your-username
# patreon: # Replace with: patreon: your-username
# tidelift: # Replace with: tidelift: your-username
# community_bridge: # Replace with: community_bridge: your-username
# liberapay: # Replace with: liberapay: your-username
# issuehunt: # Replace with: issuehunt: your-username
# otechie: # Replace with: otechie: your-username
# custom: # Replace with: custom: your-custom-link
