version: '3.8'

services:
  lambda-local:
    build:
      context: .
      dockerfile: Dockerfile.lambda
    ports:
      - "9000:8080"
    environment:
      - AWS_LAMBDA_RUNTIME_API=host.docker.internal:9000
      - AWS_LAMBDA_FUNCTION_NAME=ai-swagger-bot-api
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=1024
      - AWS_LAMBDA_FUNCTION_TIMEOUT=30
      - STAGE=local
      - PYTHONPATH=/var/task:/var/task/api:/var/task/src
    volumes:
      - ./logs:/tmp/logs
      - ./.env:/var/task/.env:ro
    command: ["lambda_handler.handler"]
    depends_on:
      - postgres
      - redis

  # PostgreSQL для локального тестування
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_swagger_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # Redis для черги завдань
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # AWS Lambda Runtime Interface Emulator
  lambda-rie:
    image: public.ecr.aws/lambda/python:3.11
    ports:
      - "9000:8080"
    environment:
      - AWS_LAMBDA_RUNTIME_API=host.docker.internal:9000
    volumes:
      - ./lambda_handler.py:/var/task/lambda_handler.py:ro
      - ./api:/var/task/api:ro
      - ./src:/var/task/src:ro
      - ./requirements.txt:/var/task/requirements.txt:ro
    command: ["lambda_handler.handler"]

volumes:
  postgres_data:
  redis_data: 