services:
  test:
    build: .
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./examples:/app/examples
    command: python -m pytest tests/ -v --cov=src --cov-report=html --cov-report=term-missing

  lint:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./examples:/app/examples
    command: |
      sh -c "
        black --check --diff src/ tests/ examples/ &&
        isort --check-only --diff src/ tests/ examples/
      "

  format:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./examples:/app/examples
    command: |
      sh -c "
        black src/ tests/ examples/ &&
        isort src/ tests/ examples/
      "
