blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/alexandrsukhryn/ai-swagger-bot/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: mailto:security@ai-swagger-bot.com
    about: Please report security vulnerabilities via email.
