"""Initial migration: create all tables

Revision ID: f175caf04ca9
Revises:
Create Date: 2025-08-09 16:27:35.237959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f175caf04ca9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("success_rate", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", "category", name="uq_user_prompt_name_category"),
    )
    op.create_index("idx_prompt_category", "prompt_templates", ["category"], unique=False)
    op.create_index("idx_prompt_public", "prompt_templates", ["is_public"], unique=False)
    op.create_index(
        "idx_prompt_user_active", "prompt_templates", ["user_id", "is_active"], unique=False
    )
    op.create_table(
        "swagger_specs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_data", sa.JSON(), nullable=False),
        sa.Column("parsed_data", sa.JSON(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("endpoints_count", sa.Integer(), nullable=True),
        sa.Column("jwt_token", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "filename", name="uq_user_filename"),
    )
    op.create_index("idx_swagger_created", "swagger_specs", ["created_at"], unique=False)
    op.create_index(
        "idx_swagger_user_active", "swagger_specs", ["user_id", "is_active"], unique=False
    )
    op.create_table(
        "api_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("swagger_spec_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_path", sa.String(length=500), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("request_data", sa.JSON(), nullable=True),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("execution_time", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["swagger_spec_id"],
            ["swagger_specs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_apicall_created", "api_calls", ["created_at"], unique=False)
    op.create_index("idx_apicall_endpoint", "api_calls", ["endpoint_path", "method"], unique=False)
    op.create_index("idx_apicall_status", "api_calls", ["status_code"], unique=False)
    op.create_index(
        "idx_apicall_user_swagger", "api_calls", ["user_id", "swagger_spec_id"], unique=False
    )
    op.create_table(
        "api_embeddings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("swagger_spec_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_path", sa.String(length=500), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("embedding", sa.Text(), nullable=False),
        sa.Column("embedding_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["swagger_spec_id"],
            ["swagger_specs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "swagger_spec_id", "endpoint_path", "method", name="uq_user_swagger_endpoint"
        ),
    )
    op.create_index("idx_embedding_created", "api_embeddings", ["created_at"], unique=False)
    op.create_index(
        "idx_embedding_method_path", "api_embeddings", ["method", "endpoint_path"], unique=False
    )
    op.create_index(
        "idx_embedding_user_swagger", "api_embeddings", ["user_id", "swagger_spec_id"], unique=False
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("swagger_spec_id", sa.String(length=36), nullable=True),
        sa.Column("session_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["swagger_spec_id"],
            ["swagger_specs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_session_created", "chat_sessions", ["created_at"], unique=False)
    op.create_index(
        "idx_session_user_active", "chat_sessions", ["user_id", "is_active"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_message_created", "chat_messages", ["created_at"], unique=False)
    op.create_index("idx_message_role", "chat_messages", ["role"], unique=False)
    op.create_index("idx_message_session", "chat_messages", ["chat_session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_message_session", table_name="chat_messages")
    op.drop_index("idx_message_role", table_name="chat_messages")
    op.drop_index("idx_message_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("idx_session_user_active", table_name="chat_sessions")
    op.drop_index("idx_session_created", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index("idx_embedding_user_swagger", table_name="api_embeddings")
    op.drop_index("idx_embedding_method_path", table_name="api_embeddings")
    op.drop_index("idx_embedding_created", table_name="api_embeddings")
    op.drop_table("api_embeddings")
    op.drop_index("idx_apicall_user_swagger", table_name="api_calls")
    op.drop_index("idx_apicall_status", table_name="api_calls")
    op.drop_index("idx_apicall_endpoint", table_name="api_calls")
    op.drop_index("idx_apicall_created", table_name="api_calls")
    op.drop_table("api_calls")
    op.drop_index("idx_swagger_user_active", table_name="swagger_specs")
    op.drop_index("idx_swagger_created", table_name="swagger_specs")
    op.drop_table("swagger_specs")
    op.drop_index("idx_prompt_user_active", table_name="prompt_templates")
    op.drop_index("idx_prompt_public", table_name="prompt_templates")
    op.drop_index("idx_prompt_category", table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_table("users")
    # ### end Alembic commands ###
