name: Quick Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  quick-lint:
    name: Quick Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 ruff

    - name: Check code formatting
      run: |
        black --check --diff src/ tests/ examples/ || echo "❌ Code formatting issues found"

    - name: Check import sorting
      run: |
        isort --check-only --diff src/ tests/ examples/ || echo "❌ Import sorting issues found"

    - name: Quick lint check
      run: |
        ruff check src/ tests/ examples/ --output-format=text || echo "❌ Ruff issues found"

  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run quick tests
      run: |
        pytest tests/ -v --tb=short --maxfail=5 || echo "❌ Tests failed"
